<?php


declare(strict_types=1);

namespace App\Filament\Resources\Users\Schemas;

use Filament\Schemas\Schema;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Toggle;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\DateTimePicker;

class UserForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('uuid')
                    ->label('UUID')
                    ->required(),
                TextInput::make('name')
                    ->required(),
                TextInput::make('middle_name'),
                TextInput::make('surname')
                    ->required(),
                TextInput::make('national_id'),
                TextInput::make('national_id_hashed'),
                Select::make('gender')
                    ->options(['f' => 'F', 'm' => 'M', 'o' => 'O']),
                TextInput::make('birth_date'),
                Select::make('hometown')
                    ->options([
            'aleppo' => 'Aleppo',
            'suwayda' => 'Suwayda',
            'damascus' => 'Damascus',
            'daraa' => 'Daraa',
            'deir-ezzor' => 'Deir ezzor',
            'hama' => 'Hama',
            'hasakah' => 'Hasakah',
            'homs' => 'Homs',
            'idlib' => 'Idlib',
            'latakia' => 'Latakia',
            'quneitra' => 'Quneitra',
            'raqqa' => 'Raqqa',
            'rif-dimashq' => 'Rif dimashq',
            'tartus' => 'Tartus',
        ]),
                TextInput::make('email')
                    ->label('Email address')
                    ->email(),
                TextInput::make('email_hashed')
                    ->email(),
                DateTimePicker::make('email_verified_at'),
                TextInput::make('phone')
                    ->tel(),
                TextInput::make('phone_hashed')
                    ->tel(),
                DateTimePicker::make('phone_verified_at'),
                TextInput::make('avatar'),
                Select::make('language')
                    ->options(['ar' => 'Ar', 'ku' => 'Ku', 'en' => 'En'])
                    ->default('ar')
                    ->required(),
                TextInput::make('google_id'),
                TextInput::make('apple_id'),
                TextInput::make('password')
                    ->password(),
                Select::make('country')
                    ->options([
            'AF' => 'A f',
            'EG' => 'E g',
            'AX' => 'A x',
            'AL' => 'A l',
            'DZ' => 'D z',
            'AS' => 'A s',
            'AD' => 'A d',
            'AO' => 'A o',
            'AI' => 'A i',
            'AQ' => 'A q',
            'AG' => 'A g',
            'GQ' => 'G q',
            'AR' => 'A r',
            'AM' => 'A m',
            'AW' => 'A w',
            'AZ' => 'A z',
            'ET' => 'E t',
            'AU' => 'A u',
            'BS' => 'B s',
            'BH' => 'B h',
            'BD' => 'B d',
            'BB' => 'B b',
            'BY' => 'B y',
            'BE' => 'B e',
            'BZ' => 'B z',
            'BJ' => 'B j',
            'BM' => 'B m',
            'BT' => 'B t',
            'BO' => 'B o',
            'BA' => 'B a',
            'BW' => 'B w',
            'BV' => 'B v',
            'BR' => 'B r',
            'IO' => 'I o',
            'BN' => 'B n',
            'BG' => 'B g',
            'BF' => 'B f',
            'BI' => 'B i',
            'CL' => 'C l',
            'CN' => 'C n',
            'CK' => 'C k',
            'CR' => 'C r',
            'CW' => 'C w',
            'DK' => 'D k',
            'CD' => 'C d',
            'DE' => 'D e',
            'DM' => 'D m',
            'DO' => 'D o',
            'DJ' => 'D j',
            'EC' => 'E c',
            'SV' => 'S v',
            'CI' => 'C i',
            'ER' => 'E r',
            'EE' => 'E e',
            'SZ' => 'S z',
            'FK' => 'F k',
            'FO' => 'F o',
            'FJ' => 'F j',
            'FI' => 'F i',
            'FM' => 'F m',
            'FR' => 'F r',
            'GF' => 'G f',
            'PF' => 'P f',
            'TF' => 'T f',
            'MC' => 'M c',
            'GA' => 'G a',
            'GM' => 'G m',
            'GE' => 'G e',
            'GH' => 'G h',
            'GI' => 'G i',
            'GD' => 'G d',
            'GR' => 'G r',
            'GL' => 'G l',
            'GP' => 'G p',
            'GU' => 'G u',
            'GT' => 'G t',
            'GG' => 'G g',
            'GN' => 'G n',
            'GW' => 'G w',
            'GY' => 'G y',
            'HT' => 'H t',
            'HM' => 'H m',
            'HN' => 'H n',
            'HK' => 'H k',
            'IN' => 'I n',
            'ID' => 'I d',
            'IM' => 'I m',
            'IQ' => 'I q',
            'IR' => 'I r',
            'IE' => 'I e',
            'IS' => 'I s',
            'IL' => 'I l',
            'IT' => 'I t',
            'JM' => 'J m',
            'JP' => 'J p',
            'YE' => 'Y e',
            'JE' => 'J e',
            'JO' => 'J o',
            'VG' => 'V g',
            'VI' => 'V i',
            'KY' => 'K y',
            'KH' => 'K h',
            'CM' => 'C m',
            'CA' => 'C a',
            'CV' => 'C v',
            'BQ' => 'B q',
            'KZ' => 'K z',
            'QA' => 'Q a',
            'KE' => 'K e',
            'KG' => 'K g',
            'KI' => 'K i',
            'UM' => 'U m',
            'CC' => 'C c',
            'CO' => 'C o',
            'KM' => 'K m',
            'XK' => 'X k',
            'HR' => 'H r',
            'CU' => 'C u',
            'KW' => 'K w',
            'LA' => 'L a',
            'LS' => 'L s',
            'LV' => 'L v',
            'LB' => 'L b',
            'LR' => 'L r',
            'LY' => 'L y',
            'LI' => 'L i',
            'LT' => 'L t',
            'LU' => 'L u',
            'MO' => 'M o',
            'MG' => 'M g',
            'MW' => 'M w',
            'MY' => 'M y',
            'MV' => 'M v',
            'ML' => 'M l',
            'MT' => 'M t',
            'MA' => 'M a',
            'MH' => 'M h',
            'MQ' => 'M q',
            'MR' => 'M r',
            'MU' => 'M u',
            'YT' => 'Y t',
            'MX' => 'M x',
            'MD' => 'M d',
            'MN' => 'M n',
            'ME' => 'M e',
            'MS' => 'M s',
            'MZ' => 'M z',
            'MM' => 'M m',
            'NA' => 'N a',
            'NR' => 'N r',
            'NP' => 'N p',
            'NC' => 'N c',
            'NZ' => 'N z',
            'NI' => 'N i',
            'NL' => 'N l',
            'NE' => 'N e',
            'NG' => 'N g',
            'NU' => 'N u',
            'KP' => 'K p',
            'MP' => 'M p',
            'MK' => 'M k',
            'NF' => 'N f',
            'NO' => 'N o',
            'OM' => 'O m',
            'AT' => 'A t',
            'TL' => 'T l',
            'PK' => 'P k',
            'PS' => 'P s',
            'PW' => 'P w',
            'PA' => 'P a',
            'PG' => 'P g',
            'PY' => 'P y',
            'PE' => 'P e',
            'PH' => 'P h',
            'PN' => 'P n',
            'PL' => 'P l',
            'PT' => 'P t',
            'PR' => 'P r',
            'CG' => 'C g',
            'RE' => 'R e',
            'RW' => 'R w',
            'RO' => 'R o',
            'RU' => 'R u',
            'MF' => 'M f',
            'SB' => 'S b',
            'ZM' => 'Z m',
            'WS' => 'W s',
            'SM' => 'S m',
            'BL' => 'B l',
            'ST' => 'S t',
            'SA' => 'S a',
            'SE' => 'S e',
            'CH' => 'C h',
            'SN' => 'S n',
            'RS' => 'R s',
            'SC' => 'S c',
            'SL' => 'S l',
            'ZW' => 'Z w',
            'SG' => 'S g',
            'SX' => 'S x',
            'SK' => 'S k',
            'SI' => 'S i',
            'SO' => 'S o',
            'ES' => 'E s',
            'LK' => 'L k',
            'SH' => 'S h',
            'KN' => 'K n',
            'LC' => 'L c',
            'PM' => 'P m',
            'VC' => 'V c',
            'ZA' => 'Z a',
            'SD' => 'S d',
            'GS' => 'G s',
            'KR' => 'K r',
            'SS' => 'S s',
            'SR' => 'S r',
            'SJ' => 'S j',
            'SY' => 'S y',
            'TJ' => 'T j',
            'TW' => 'T w',
            'TZ' => 'T z',
            'TH' => 'T h',
            'TG' => 'T g',
            'TK' => 'T k',
            'TO' => 'T o',
            'TT' => 'T t',
            'TD' => 'T d',
            'CZ' => 'C z',
            'TN' => 'T n',
            'TR' => 'T r',
            'TM' => 'T m',
            'TC' => 'T c',
            'TV' => 'T v',
            'UG' => 'U g',
            'UA' => 'U a',
            'HU' => 'H u',
            'UY' => 'U y',
            'UZ' => 'U z',
            'VU' => 'V u',
            'VA' => 'V a',
            'VE' => 'V e',
            'AE' => 'A e',
            'US' => 'U s',
            'GB' => 'G b',
            'VN' => 'V n',
            'WF' => 'W f',
            'CX' => 'C x',
            'EH' => 'E h',
            'CF' => 'C f',
            'CY' => 'C y',
        ]),
                TextInput::make('province'),
                Toggle::make('shelter'),
                Textarea::make('address')
                    ->columnSpanFull(),
                Select::make('education_level')
                    ->options([
            'none' => 'None',
            'primary' => 'Primary',
            'secondary' => 'Secondary',
            'high-school' => 'High school',
            'university-degree' => 'University degree',
            'postgraduate' => 'Postgraduate',
        ]),
                Textarea::make('skills')
                    ->columnSpanFull(),
                Select::make('marital_status')
                    ->options([
            'single' => 'Single',
            'married' => 'Married',
            'divorced' => 'Divorced',
            'widowed' => 'Widowed',
            'separated' => 'Separated',
            'engaged' => 'Engaged',
            'in-a-relationship' => 'In a relationship',
            'complicated' => 'Complicated',
            'other' => 'Other',
        ]),
                Select::make('source_of_income')
                    ->options([
            'stable-job' => 'Stable job',
            'freelance' => 'Freelance',
            'aid-support' => 'Aid support',
            'no-income' => 'No income',
            'other' => 'Other',
        ]),
                TextInput::make('estimated_monthly_income')
                    ->numeric(),
                TextInput::make('number_of_dependents')
                    ->numeric(),
                Select::make('health_status')
                    ->options([
            'good' => 'Good',
            'chronic-illness' => 'Chronic illness',
            'disabled-special-needs' => 'Disabled special needs',
        ]),
                Toggle::make('health_insurance'),
                Toggle::make('easy_access_to_healthcare_services'),
                Select::make('ethnicity')
                    ->options([
            'arab' => 'Arab',
            'kurd' => 'Kurd',
            'greek' => 'Greek',
            'assyrian' => 'Assyrian',
            'armenian' => 'Armenian',
            'turkmen' => 'Turkmen',
            'chechen' => 'Chechen',
            'circassian' => 'Circassian',
            'other' => 'Other',
        ]),
                Select::make('religious_affiliation')
                    ->options([
            'sunni' => 'Sunni',
            'shia' => 'Shia',
            'alawites' => 'Alawites',
            'ismailis' => 'Ismailis',
            'druze' => 'Druze',
            'greek-orthodox' => 'Greek orthodox',
            'greek-catholic' => 'Greek catholic',
            'protestant' => 'Protestant',
            'syriac-orthodox' => 'Syriac orthodox',
            'syriac-catholic' => 'Syriac catholic',
            'armenian-orthodox' => 'Armenian orthodox',
            'armenian-catholic' => 'Armenian catholic',
            'assyrian-church-of-the-east' => 'Assyrian church of the east',
            'maronites' => 'Maronites',
            'jews' => 'Jews',
            'yazidis' => 'Yazidis',
            'non-religious' => 'Non religious',
            'other' => 'Other',
        ]),
                Textarea::make('communication')
                    ->columnSpanFull(),
                Textarea::make('more_info')
                    ->columnSpanFull(),
                Textarea::make('other_nationalities')
                    ->columnSpanFull(),
                Textarea::make('languages')
                    ->columnSpanFull(),
                DateTimePicker::make('verified_at'),
                Select::make('verification_reason')
                    ->options(['first_registrant' => 'First registrant', 'verifiers' => 'Verifiers']),
                DateTimePicker::make('marked_as_fake_at'),
                Textarea::make('marked_as_fake_reason')
                    ->columnSpanFull(),
                TextInput::make('record_place'),
                TextInput::make('record_id'),
                TextInput::make('facebook_link'),
                TextInput::make('twitter_link'),
                TextInput::make('linkedin_link'),
                TextInput::make('github_link'),
                TextInput::make('instagram_link'),
                TextInput::make('snapchat_link'),
                TextInput::make('tiktok_link'),
                TextInput::make('youtube_link'),
                TextInput::make('pinterest_link'),
                TextInput::make('twitch_link'),
                TextInput::make('website')
                    ->url(),
                Toggle::make('received_verification_email')
                    ->required(),
                Toggle::make('account_verified_email')
                    ->required(),
                TextInput::make('two_factor_secret'),
                Toggle::make('two_factor_enabled')
                    ->required(),
                DateTimePicker::make('two_factor_confirmed_at'),
                TextInput::make('recovery_codes'),
                TextInput::make('recovery_codes_total')
                    ->numeric(),
            ]);
    }
}
