<?php


declare(strict_types=1);

namespace App\Filament\Resources\Users\Schemas;

use App\Models\User;
use Filament\Schemas\Schema;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;

class UserInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('uuid')
                    ->label('UUID'),
                TextEntry::make('name'),
                TextEntry::make('middle_name')
                    ->placeholder('-'),
                TextEntry::make('surname'),
                TextEntry::make('national_id')
                    ->placeholder('-'),
                TextEntry::make('national_id_hashed')
                    ->placeholder('-'),
                TextEntry::make('gender')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('birth_date')
                    ->placeholder('-'),
                TextEntry::make('hometown')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label('Email address')
                    ->placeholder('-'),
                TextEntry::make('email_hashed')
                    ->placeholder('-'),
                TextEntry::make('email_verified_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('phone')
                    ->placeholder('-'),
                TextEntry::make('phone_hashed')
                    ->placeholder('-'),
                TextEntry::make('phone_verified_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('avatar')
                    ->placeholder('-'),
                TextEntry::make('language')
                    ->badge(),
                TextEntry::make('google_id')
                    ->placeholder('-'),
                TextEntry::make('apple_id')
                    ->placeholder('-'),
                TextEntry::make('country')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('province')
                    ->placeholder('-'),
                IconEntry::make('shelter')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('education_level')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('skills')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('marital_status')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('source_of_income')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('estimated_monthly_income')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('number_of_dependents')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('health_status')
                    ->badge()
                    ->placeholder('-'),
                IconEntry::make('health_insurance')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('easy_access_to_healthcare_services')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('ethnicity')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('religious_affiliation')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('communication')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('more_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('other_nationalities')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('languages')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('verified_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('verification_reason')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('marked_as_fake_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('marked_as_fake_reason')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('record_place')
                    ->placeholder('-'),
                TextEntry::make('record_id')
                    ->placeholder('-'),
                TextEntry::make('facebook_link')
                    ->placeholder('-'),
                TextEntry::make('twitter_link')
                    ->placeholder('-'),
                TextEntry::make('linkedin_link')
                    ->placeholder('-'),
                TextEntry::make('github_link')
                    ->placeholder('-'),
                TextEntry::make('instagram_link')
                    ->placeholder('-'),
                TextEntry::make('snapchat_link')
                    ->placeholder('-'),
                TextEntry::make('tiktok_link')
                    ->placeholder('-'),
                TextEntry::make('youtube_link')
                    ->placeholder('-'),
                TextEntry::make('pinterest_link')
                    ->placeholder('-'),
                TextEntry::make('twitch_link')
                    ->placeholder('-'),
                TextEntry::make('website')
                    ->placeholder('-'),
                IconEntry::make('received_verification_email')
                    ->boolean(),
                IconEntry::make('account_verified_email')
                    ->boolean(),
                TextEntry::make('two_factor_secret')
                    ->placeholder('-'),
                IconEntry::make('two_factor_enabled')
                    ->boolean(),
                TextEntry::make('two_factor_confirmed_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('recovery_codes_total')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('deleted_at')
                    ->dateTime()
                    ->visible(fn (User $record): bool => $record->trashed()),
            ]);
    }
}
