#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "▶️ Running tests..."

if ! php artisan test; then
  echo "❌ Tests failed. Commit aborted."
  exit 1
fi

echo "✅ Tests passed. Proceeding with commit."
